### PR TITLE
Rewrite for atom-linter

### LINKED ISSUE #7: Doesn't work at all for me.
It just says "no issues" all the time.

I do have swiftlint working in Xcode so this is kind of strange.

### PR DESCRIPTION
**Pull request by norio-nomura**
will fix #7

### CODE REVIEW

**Comment by keplersj** [comment]
Looking good.

**Comment by keplersj** [comment]
@norio-nomura If you're interested in helping maintain this just ask @steelbrain.

**Comment by norio-nomura** [comment]
Thanks for merging and release :pray:
I'll file PRs if I feel I needs it. :smiley:

**Comment by keplersj** [comment]
Good to hear it. :grinning:

**Pull request merged**
