### PR TITLE
Fix regex for using stdin

### LINKED ISSUE #10: > 0 issue count but no issues shown in file
Clicking on the issue count results in a new file with the name <nopath>.

### PR DESCRIPTION
**Pull request by norio-nomura**
Fix #10

### CODE REVIEW

**Comment by steelbrain** [comment]
Can you please explain the error in detail? That bug report is lacking even the basic information

**Comment by norio-nomura** [comment]
SwiftLint has `--use-stdin` option that read contents from stdin. On that case, output is following format:

```
<nopath>:22:36: warning: Force Unwrapping Violation: Force unwrapping should be avoided. (force_unwrapping)
```

linter-swiftlint 1.0.0 uses `helpers.parse` as [following](https://github.com/AtomLinter/linter-swiftlint/blob/master/lib%2Finit.coffee#L41)

``` coffee
          helpers.parse(output, regex, {filePath: filePath})
```

On atom-linter 3.3.9, that treated `filePath` option as following:

``` coffee
        filePath = match.file
        filePath = options.filePath if options.filePath
```

On atom-linter 3.4.1 that installed by "^3.2.0" has been changed as following:

``` js
    const file = match.file || options.filePath || null;
```

That caused file = `"<nopath>"` on linter issue pane, clicking it make Atom opens new file.

**Comment by steelbrain** [comment]
I don't think that's the problem

``` js
> var match = {file: null}
> var options = {filePath: "Something"}
> var file = match.file || options.filePath || null
> console.log(file)
< "Something"
```

**Comment by steelbrain** [comment]
If I had to guess, it's a problem somewhere in the regexp, it could be providing it an empty string with a length of 1 or more

**Comment by norio-nomura** [comment]
The regex is following:

``` coffee
    regex = '(?<file>[^:]+):(?<line>\\d+):(?<col>\\d+)?:?\\s(?<type>\\w+):\\s(?<message>.*)'
```

then `match.file` is not `null`, `match.file = "<nopath>"`.

**Comment by steelbrain** [comment]
Ah! We should be rejecting that `<nopath>` then, we shouldn't be matching it with the regex. The update of `atom-linter` actually fixes this, the options parameter is sort-of the defaults for each match. It tries to find the file from the match, if there isn't any, it picks a default from the options.

Instead of changing the priorities to un-desired ones, I think we should be correcting the regexp

**Comment by norio-nomura** [comment]
Ok, I'll rewrite it.

**Comment by steelbrain** [comment]
@amichail Can you confirm this fixes the problem for you?

**Comment by Arcanemagus** [comment]
@norio-nomura can you squish your commits?

**Comment by Arcanemagus** [comment]
Since we are now using `stdin` exclusively, is there any reason to still capture the file path?

**Comment by keplersj** [comment]
@Arcanemagus I'm going to let you and @steelbrain merge this in when you feel it's ready.

**Comment by norio-nomura** [comment]
Thank you for reviews.
Just updated.

**Comment by keplersj** [comment]
Nice.

**Comment by norio-nomura** [comment]
:pray:

**Comment by amichail** [comment]
Looks good! Thanks!

**Pull request merged**
